### ISSUE TITLE
Strings are spread in logs causing column indexing to increase unnecessarily 

### ISSUE THREAD

**Issue by crobinson42** [logtail/logtail-js#16]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/5973579/180331376-c98c208a-882e-4976-a59d-7444107e39f9.png">

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/5973579/180331315-83508683-f4b4-4183-92ab-b9cdef18714b.png">

**Comment by gyfis** [comment]
Hi @crobinson42, thanks for raising the issue! Can you share a bit more about your set-up, or a small reproducible script? Thanks a lot!

**Comment by crobinson42** [comment]
@gyfis I don't know what to share with you except that I'm using the latest npm package with Node.js v16. As you can see in the first screenshot I am passing a string, `event`, as the second arg and it's being spread in the logtail sdk.

**Comment by gyfis** [comment]
> @gyfis I don't know what to share with you except that I'm using the latest npm package with Node.js v16. As you can see in the first screenshot I am passing a string, `event`, as the second arg and it's being spread in the logtail sdk.

Thanks for that extra info, I understand the issue now (I missed that the event was a String).

We expect an object as the second argument (think: structured context for the log), and due to the nature of JavaScript, String does this.

I’m adding this to our pipeline; in the meantime, can you use an object instead of the string event? If you want to pass a string, you can always do `{ event: event }`. Thanks!
