### ISSUE TITLE
Better syntax for chained dot notation of a Context type when using typescript

### ISSUE THREAD

**Issue by egegungordu** [logtail/logtail-js#21]
Writing typesafe procedures when dealing with the Context type feels very weird and I was wondering if it can be improved?

An example from my app:
```typescript
// add runtime env information through a middleware
logtail.use(async (log) => {
  if (log.context && (log.context as Context).runtime) {
    const runtime = (log.context as Context).runtime as Context;
    runtime.env = process.env.NODE_ENV;
    const messagePrefix = process.env.NODE_ENV === "production" ? "" : "[DEV] ";
    log.message = messagePrefix + log.message;
  }
  return {
    ...log,
  };
});
```

A lot of `as Context`'s are needed to access the children in the context. Instead of this, being able to do this would be better:

```typescript
// add runtime env information through a middleware
logtail.use(async (log) => {
  if (log.context && log.context.runtime) {
    log.context.runtime.env = process.env.NODE_ENV;
    const messagePrefix = process.env.NODE_ENV === "production" ? "" : "[DEV] ";
    log.message = messagePrefix + log.message;
  }
  return {
    ...log,
  };
});
```

Is implementing this type possible?

**Comment by curusarn** [comment]
Hi @egegungordu,

Thanks for bringing this up. I passed it on to the team.
I will make sure to keep you updated.

**Comment by PetrHeinz** [comment]
Hi @egegungordu,

thanks for opening the issue. We originally thought strongly typed context would help devs to know what kinds of types can be safely used, but the added complexity of use is really not worth it.

Since `v0.4.6` you access children in the context just in the way you've described 👍 

Thank you for your patience 🙏  Feel free to reopen the issue if something feels off or you have any question.
