### ISSUE TITLE
Missing latest logs

### ISSUE THREAD

**Issue by wesleyyee** [logtail/logtail-js#26]
Some logs do not appear unless additional logs come later. Seems as if there are some logs that are not synced until more come in. The _countLogged and _countSynced do seem to suggest this? It is also worth noting that this is running in a lambda function. The logger object shows:

```_middleware: [],
  _countLogged: 18,
  _countSynced: 17,
  _sourceToken: 'cGMBz7ikULX7EnL8mW7ADHEt',
  _options: {
    endpoint: 'https://in.logtail.com',
    batchSize: 1000,
    batchInterval: 1000,
    syncMax: 10,
    ignoreExceptions: true
  },```

**Comment by gyfis** [comment]
@wesleyyee Hi, thanks for raising the issue! 

Since our JavaScript logging library is async-based, it's possible the Lambda runtime ends before the last logs have a chance to get sent. One solution is to `.await` the last logging line at the end of your Lambda function - that will ensure that the queued logs will be processed.

Closing as this is a known Lambda runtime behavior. Let us know if there's anything else we can help with, either here or at hello@logtail.com!
