### ISSUE TITLE
[node] Minimal required node.js version

### ISSUE THREAD

**Issue by Quentintin** [logtail/logtail-js#3]
Hello.
I tried to install and setup this package on legacy code using Node.js 8.17.0
No surprise, it does'nt work! (as usual) because of `@msgpack/msgpack` needing Node v10 at least. (`for async` did not exists)

Do you have any solution to make it works in my situation ?

Also, it should be good to add **`Node.js requirements`** section into README file

Thank you 😃

**Comment by gyfis** [comment]
> Hello. I tried to install and setup this package on legacy code using Node.js 8.17.0 No surprise, it does'nt work! (as usual) because of `@msgpack/msgpack` needing Node v10 at least. (`for async` did not exists)
> 
> Do you have any solution to make it works in my situation ?
> 
> Also, it should be good to add **`Node.js requirements`** section into README file
> 
> Thank you 😃

Hi Quentintin (@Quentintin )! Thanks for your question, and I'm sorry it took us such a long time to get to it.

We'll be updating READMEs of our clients soon, and I'll be sure to mention the required versions - that's a great suggestion!

As for Node support, while you may have had success running on v10, we support the LTS node versions - which means v12+ at the moment. Due to time requirements, I'm afraid we're not able to support other versions at the moment. We do accept PRs, though - so if you have a quick fix that will help you, submit a pull request and we'll take a look. Thanks!
