### ISSUE TITLE
Error logging with 0.4.0

### ISSUE THREAD

**Issue by ryenbeatty** [logtail/logtail-js#58]
Hi all, I'm seeing this error message, do you have any idea what the cause could be?

```
Error: Forbidden
    at Node.sync [as _sync] (/Users/ryenbeatty/Code/project/node_modules/@logtail/node/dist/cjs/node.js:28:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

My config:
```
import { Browser, Node } from '@logtail/js'

const clientLogger = new Browser(process.env.NEXT_PUBLIC_LOGTAIL_SOURCE_TOKEN)
const serverLogger = new Node(process.env.NEXT_PUBLIC_LOGTAIL_SOURCE_TOKEN)

export { clientLogger, serverLogger }
```

**Comment by curusarn** [comment]
Hi @ryenbeatty,

Thank you for reaching out.

Forbidden errors are usually caused by the source token being wrong.
Is it possible that the env variable NEXT_PUBLIC_LOGTAIL_SOURCE_TOKEN is not set to the correct token value for your Logtail source?

Could you check that the token is set properly? 🙏

Thanks again for bringing this up.

Simon

**Comment by ryenbeatty** [comment]
Hi Simon,

Yes it is possible, in fact the `NEXT_PUBLIC_LOGTAIL_SOURCE_TOKEN` is only available in the browser so that would explain it!

I'll close this one for now, thanks for the help.

**Comment by curusarn** [comment]
Hi @ryenbeatty,

One more thing I forgot to mention earlier. If you are using Vercel or Next.js you can use our dedicated Next.js logging client. Docs on how to set it up: https://betterstack.com/docs/logs/vercel/#optional-structured-logging

If you need help integrating with Logtail, do not hesitate to message us as hello@logtail.com. 🙏 
We're happy to help!

Simon
