### ISSUE TITLE
Add ability to color log outputs

### ISSUE THREAD

**Issue by jakeleventhal** [logtail/logtail-js#64]

**Comment by curusarn** [comment]
Hi @jakeleventhal,

Thanks for reaching out.

Would you mind sharing some more details?
How do you imagine coloring output would work? Would you want to see colorful output in terminal? Or would you like to configure and see different colors in Live tail?

Let me know your thoughts. 🙏

Simon

**Comment by PetrHeinz** [comment]
Hi @jakeleventhal 

Better Stack Logs supports some [ANSI codes](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) in log message, so you can them to make parts of your log different color, bold etc. Not everything is supported out of the box though (eg. because of different contrasts in light/dark mode):

```js
logger.info("Logs can be \033[1mbold\033[0m, \033[31mred\033[0m, or \033[1;32mbold green,\033[0m.");
```

Result in Better Stack:

![image](https://github.com/logtail/logtail-js/assets/10008612/1c91aa08-b2eb-4e01-a97b-110a854dd718)

Result in console with `{ sendLogsToConsoleOutput: true }`:

<img width="370" alt="image" src="https://github.com/logtail/logtail-js/assets/10008612/dbe5ad49-50d2-4704-9bbb-1c758e1ad890">

**Comment by jakeleventhal** [comment]
I suppose what I'm not getting is how you are styling the log type automatically
<img width="73" alt="Screenshot 2023-09-14 at 9 21 10 AM" src="https://github.com/logtail/logtail-js/assets/15133828/58474d4d-2d91-4b9b-a911-c43946b15aef">

**Comment by PetrHeinz** [comment]
@jakeleventhal level fields (level, severity, message.level, log.level, or outcome) are automatically colored by Better Stack based on their severity. In JS, it really just depends on whether you use for example `logger.info` or `logger.warn`

**Comment by dsbudiac** [comment]
Is there a recommended library for logging colors? I'm using chalk with some hex colors, and they're not rendering in BetterStack i.e.

```ts
import { randomBytes } from 'crypto'
import chalk from 'chalk'

const randomHex = randomBytes(20).toString('hex').substring(0,6)

logger.info(`Here is a message with some ${chalk.hex(randomHex)('color')}`)
```

**Comment by dsbudiac** [comment]
I got the following to work:

```ts
import styles from 'ansi-styles'
import { randomBytes } from 'crypto'

const hex = randomBytes(3).toString('hex')
const ansi = styles.hexToAnsi('#' + hex)
const random = styles.color.ansi(ansi)

const message = `Here is some ${styles.red.open}red${styles.reset.close} and ${random}random hex #${hex}${styles.reset.close}`

logger.info(message)
```

Also it seems chalk and default `styles.color.close` in `ansi-styles` escapes differently than what BetterStack wants. Need to do a full reset after each color.
