### ISSUE TITLE
Logtail blocked by adblocker

### ISSUE THREAD

**Issue by michaelw85** [logtail/logtail-js#74]
Hi,

I'm implementing logtail in a project and noticed it's being blocked.
![image](https://github.com/logtail/logtail-js/assets/3629094/a057ab4d-0c2a-4da0-910b-0148ff17d7ea)

I'm using Brave browser which blocks a lot by default. I've seen it block certain things purely based on names in files.
I think (assumption) it's blocking based on the word "log" in the url.

If anyone would like to add an exception this UBlock syntax works for me:
```
@@||in.logtail.com
```

**Comment by PetrHeinz** [comment]
Hello, thanks for opening the issue and posting a workaround 👍 

Since preventing logging is one of Brave's features, I believe we won't be doing anything on our part to try to circumvent it. If you really want to ensure logs would get through, you can set up a proxy server and modify the `endpoint` option:

```js
const logger = new Logtail("source-token", { endpoint: "https://my-innocent-website/messages" })
```

And just a heads up, the default endpoint has changed from `in.logtail.com` to `in.logs.betterstack.com` in recent version, you should add it to your UBlock exception so you avoid debugging down the line in the future.

---

Since it's a feature of some privacy-centered browser, I'm closing the issue. I'm glad that the workaround is there for people to find easily 🙂

**Comment by PetrHeinz** [comment]
Thanks for the idea of mentioning it in the docs @michaelw85, makes sense. I added it to our [JavaScript quick start guide](https://betterstack.com/docs/logs/javascript/install/#additional-information).
