### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by songinnight** [logtail/logtail-js#76]
Node.js Version: `20.5.1`
Package Version: @logtail/node `0.4.6` (from npm)

After sending the log data, following console error appears.

```
(node:3878) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at TLSSocket.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:904:35)
    at TLSSocket._wrapHandle (node:_tls_wrap:674:8)
    at TLSSocket.reinitializeHandle (node:_tls_wrap:683:22)
    at internalConnectMultiple (node:net:1123:30)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by PetrHeinz** [comment]
Hello @songinnight and thanks for reporting the issue 🙌 

Could you please provide some steps to reproduce or some minimal script that triggers the issue? 

The error you've provided seems to be from the built-in `events` module, but there's no direct call to `addEventListener` in our codebase (except `logtail/browser`). I don't see where we could forget to unsubscribe an event listener, and I'm not sure where to start debugging without a reproducible error.

I assume the error appears only when `logtail/node` is used, right?

Have you tried slightly increasing the max listeners limit (eg. from 10 to 12), to see whether the issue persists?

**Comment by PetrHeinz** [comment]
It seems it might be caused by an issue in `node-fetch` dependency (see https://github.com/node-fetch/node-fetch/issues/1295)...

I might have an idea what can we do about it from our side, but a way of reproducing the issue would be very helpful to verify.

Using `import 'cross-fetch/polyfill';` instead of `import fetch from "cross-fetch";` should prevent Node from using `node-fetch` and use built-in `fetch` instead.
It's just an idea on my part though, and I'll need to investigate a bit more.

**Comment by PetrHeinz** [comment]
Thanks @songinnight for getting back to us 🙌  Glad it doesn't cause any issues for you.

If you ever reproduce the issue, feel free to reopen the issue so we can fix whatever might be wrong with the dependencies 🙏
